name: Release Obsidian plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "latest"

      - name: Build plugin
        run: |
          npm install
          npm run build


      - name: Package plugin
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          zip "obsidian-open-new-tab-${tag}.zip" main.js manifest.json styles.css

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip

